spring.application.name=order-service-example

tracelog.enabled=true
tracelog.sink.pretty-print=true
tracelog.trace-id.format=ulid
tracelog.trace-id.propagation-header=X-Trace-Id
tracelog.buffer.max-events-per-trace=1000
tracelog.buffer.orphan-scan-interval-seconds=5

server.port=8085
